 - name : Deploying application in tomcat server
   hosts: localhost
   become_user: root
   become: yes
   tasks:
    - name: updating the repo
      yum:
        name: '*'
        state: latest
    - name: downloading java package from repo
      yum:
        name: java-1.8.0
        state: present
    - name: Downloading tomcat package
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.tar.gz
        dest: /opt/apache-tomcat-9.0.90.tar.gz
        mode: '777'
    - name: Unziping the tomcat file 
      ansible.builtin.unarchive:
        src: /opt/apache-tomcat-9.0.90.tar.gz
        dest: /opt/
        remote_src: yes
    - name: starting the tomcat application
      ansible.builtin.shell: nohup /opt/apache-tomcat-9.0.90/bin/startup.sh &
    
    - name: copying file from master to slave for deployment 
      copy:
        src: /home/ansible/SampleWebApp.war
        dest: /opt/apache-tomcat-9.0.90/webapps
        mode: '777'
    - name: stopping the tomcat application
      ansible.builtin.shell: nohup /opt/apache-tomcat-9.0.90/bin/stutdown.sh &

    - name: starting the tomcat application
      ansible.builtin.shell: nohup /opt/apache-tomcat-9.0.90/bin/startup.sh &
